image: node:latest
stages:
  - deploy

deploying:
  stage: deploy
  variables:
    IMAGE: fernandoa12/vitavi-backend:$CI_COMMIT_SHORT_SHA
    APP: vitavi-backend
  environment:
    name: production-$CI_COMMIT_SHA
    url: $CI_PROJECT_NAME.$HOST_BACKEND
  script:
    - export NODE_ENV=deployment; yarn
    - npx jest --bail --passWithNoTests --force-exit
    - npx tsc
    - echo $DOCKER_PASSWORD | sudo docker login -u $DOCKER_USER --password-stdin
    - sudo docker build -t $IMAGE .
    - sudo docker push $IMAGE
    - $K8S_ACCESS "sudo kubectl set image deployment/$APP $APP=$IMAGE -n ingress"
    - sudo docker rmi $(sudo docker images --filter=reference="$IMAGE") || true
  only:
    - master
